application: static-engine
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static/

skip_files:
- node_modules/.*$
- bower_components/.*$
- libs/.*\.dist-info/.*$
